function [ hstruct ] = pmf_LineIinjdAPHz4(fignum, SrcStruct)
% 
% Copyright (C) 2016 by Yuichi Takeuchi

% Parameters
fontname = 'Arial';
fontsize = 10;

hfig = figure(fignum);
hold on

for l = 1:5
    SrcTb = SrcStruct(l).deltaPN;
    X = SrcTb.Iinj;
    plot(X,SrcTb.Mean, 'k', 'LineWidth', (0.5*l))
end
hold off
haxes = gca;
grid(haxes,'off');

if fignum < 2
    titlestr = 'skin';
else
    titlestr = 'skull';
end
htitle = title(titlestr);

hxlabel = xlabel('Injected current (pA, DC)');
hylabel = ylabel('\Delta Firing rate (Hz)');
hlegend = legend({...
    '0 µA',...
    '200 µA',...
    '400 µA',...
    '600 µA',...
    '800 µA',...
    });

set(hfig,...
    'PaperUnits', 'centimeters',...
    'PaperPosition', [7 7 12 6]...
    );

set(haxes,...
    'Box', 'off',...
    'YLim', [-12 12],...
    'FontName', fontname,...
    'FontSize', fontsize...
    );

set(hxlabel,...
    'HorizontalAlignment', 'center'...
    );

set(hylabel,...
    'HorizontalAlignment', 'center'...
    );

set(hlegend,...
    'Box', 'off',...
    'FontSize', fontsize,...
    'Location','northeastoutside'...
    );

hstruct.hfig = hfig;
hstruct.haxes = haxes;
hstruct.hxlabel = hxlabel;
hstruct.hylabel = hylabel;
hstruct.htitle = htitle;
hstruct.hlegend = hlegend;