function [hstruct] = pmf_BarSpike3(SrcTb1, SrcTb2, fignum, groupwidth)
% 
% 
% Copyright (C) 2016 by Yuichi Takeuchi

% Parameters
fontname = 'Arial';
fontsize = 12;

Mean = [SrcTb1.Mean, SrcTb2.Mean];
Std = [SrcTb1.Std, SrcTb2.Std];
Intensity = SrcTb1.Intensity;

hfig = figure(fignum);
% hfig = gcf;
hbar = bar(Intensity, Mean);
haxes = gca;
hold(haxes, 'on');

[~, csize]  = size(Mean);
% groupwidth = min(0.8, csize/(csize+1.5));
for i = 1:csize
      % Based on barweb.m by Bolu Ajiboye from MATLAB File Exchange
      X = Intensity - groupwidth/2 + (2*i-1) * groupwidth / (2*csize);  % Aligning error bar with individual bar
      heb = errorbar(X, Mean(:,i), Std(:,i), Std(:,i), 'linestyle', 'none', 'Color',[0 0 0]);
end

hxlabel = xlabel('Stimulus intensity (µA, DC)');
hylabel = ylabel('\Delta Firing rate (Hz)');
hold(haxes,'off');
grid(haxes,'off');

hlegend = legend({...
    'skin',...
    'skull'...
    });

set(hfig,...
    'PaperUnits', 'centimeters',...
    'PaperPosition', [7 7 12 9]...
    );

set(haxes,...
    'XLim', [-875, 875],...
    'XTick',[-800 -600 -400 -200 0 200 400 600 800],...
    'XTickLabelRotation',45,...
    %{
     'YTick',[-0.015 -0.01 -0.005 0 0.005 0.01 0.015],...
%    'YTickLabel',{'-15','-10','-5','0','5','10','15'},...
    %}
    'YLim', [-15, 35],...
    'FontName', fontname,...
    'FontSize', fontsize,...
    'Box', 'on'...
    );

set(hbar,...
    'BarWidth', 1.0...
    );

set(hxlabel,...
    'HorizontalAlignment', 'center'...
    );

set(hylabel,...
    'HorizontalAlignment', 'center'...
    );

set(hlegend,...
    'Box', 'off',...
    'FontSize', fontsize,...
    'Location','northwest'...
    );

% constructing output handle structure
hstruct.hfig = hfig;
hstruct.haxes = haxes;
hstruct.hbar = hbar;
hstruct.heb = heb;
hstruct.hxlabel = hxlabel;
hstruct.hylabel = hylabel;
% hstruct.htitle = htitle;
hstruct.hlegend = hlegend;