function [ hstruct ] = pmf_LineRinput2( fignum, SrcStruct )
% 
% Copyright (C) 2016 by Yuichi Takeuchi

% Parameters
fontname = 'Arial';
fontsize = 12;

hfig = figure(fignum);
htitle = title('');
hxlabel = xlabel('Stimulus intensity (µA, DC)');
hylabel = ylabel('Input membrane resistance (MOhm)');
% hylabel = ylabel('Input membrane resistance (M\Omega)');

hold on
recvec = [1:4, 7, 10:13];
linespec = {'-ok', '-sk', '-^k'};
current = {'30', '60', '90'};
for k = 1:3
        eval(['SrcTb = SrcStruct.Iinj' current{k} ';'])
        xvec = SrcTb.Intensity(recvec);
        meanvec = SrcTb.Mean(recvec);
        stdvec = SrcTb.Std(recvec);
        hebar = errorbar(xvec, meanvec, stdvec, linespec{k}); 
end
hold off

hlegend = legend({'-30 pA injection', '-60 pA injection', '-90 pA injection'}, ...
    'Location', 'best',...
    'box', 'off'...
    );

haxes = gca;
grid(haxes,'off');

set(hfig,...
    'PaperUnits', 'centimeters',...
    'PaperPosition', [7 7 9 6]...
    );

set(haxes,...
    'XLim', [-900 900],...
    'XTick',...
    linspace(-800,800,9),...
    'XTickLabel',{'-800','-600','-400','-200','0','200','400','600','800'},...
    'YTick',...
    [-250e6 -200e6 -150e6 -100e6 -50e6 0 50e6 100e6 150e6 200e6 250e6],...
    'YTickLabel',{'-250','-200','-150','-100','-50','0','50','100','150','200','250'},...
    'FontName', fontname,...
    'FontSize', fontsize...
    );

set(htitle,...
    'FontName', fontname,...
    'FontSize', (fontsize + 2)...
    );

set(hxlabel,...
    'HorizontalAlignment', 'center'...
    );

set(hylabel,...
    'HorizontalAlignment', 'center'...
    );

hstruct.hfig = hfig;
hstruct.haxes = haxes;
hstruct.ebar = hebar;
hstruct.hxlabel = hxlabel;
hstruct.hylabel = hylabel;
hstruct.htitle = htitle;
hstruct.hlegend = hlegend;
